version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678